### ISSUE TITLE
Visual feedback when collecting powerups

### ISSUE THREAD

**Issue by IanTeo** [yamgent/game-off-frog-game#16]
We should add some visual feedback when user collects powerups to tell user what effects they have gained. For example, when collecting a power up to increase speed, we can display "Increase Speed" on the screen (where the item is collected).

* Similar to how the points are displayed in super mario (https://www.youtube.com/watch?v=923YDMHbOsA)
![image](https://user-images.githubusercontent.com/12381148/69496246-0fa8d080-0f0b-11ea-92a5-d9733427ff63.png)

**Comment by initialshl** [comment]
Not sure how to do this. Tried attaching a world space canvas to SpeedUpItem, but the text was huge.

**Comment by IanTeo** [comment]
I think that is how they do it normally. They use super small text (in terms of the canvas). Maybe you can see how people attach HP bar to their objects. I think it is the same idea

**Comment by initialshl** [comment]
I tried font size 1 and its still big. I think our world is too small

**Comment by yamgent** [comment]
Is the content of the text ever going to change? If not, maybe it can be a sprite instead? Just draw out the text and put it as a sprite. Then you can also add effects to the text itself.

Otherwise can the font size be in decimals? Then just use 0.5 or 0.01.
