### ISSUE TITLE
Add powerup for frog

### ISSUE THREAD

**Issue by IanTeo** [yamgent/game-off-frog-game#7]
Currently, the camera will outpace and kill the frog at around 80 rows.
We should add some powerup mechanics to allow the player to progress further if they play well.

- How should the powerups be implemented?

**Comment by yamgent** [comment]
Item manager implemented in #11 but does not seem to spawn from time to time?

**Comment by initialshl** [comment]
Yeah I implemented it but didnt do the spawning yet lol
